from .db import db 


class Record(db.Model):
    __tablename__ = 'records'
    id = db.Column(db.Integer, primary_key=True)
    created_on = db.Column(db.Date)
    customer_id = db.Column(db.String(50))
    policyNumber = db.Column(db.String(50))
    referralId = db.Column(db.Integer)
    accountCreateDate = db.Column(db.DateTime)
    igoDate = db.Column(db.DateTime)
    offerDate = db.Column(db.DateTime)
    applicationSignedDate = db.Column(db.DateTime)
    issuedDate = db.Column(db.DateTime)
    status = db.Column(db.String(100))
    paidToDate = db.Column(db.DateTime)
    pending_ir = db.Column(db.Integer)
    canceled_ir = db.Column(db.Integer)
    declined_ir = db.Column(db.Integer)
    monthlyPremium = db.Column(db.Float)
    faceAmount = db.Column(db.Integer)
    term = db.Column(db.Integer)
    finalRateClass = db.Column(db.Integer)
    finalRateClassName = db.Column(db.String(50))
    paidSource = db.Column(db.String(50))
    paidSource_campaign = db.Column(db.String(50))
    telesalesAgency = db.Column(db.String(50))
    agentName = db.Column(db.String(50))
    product = db.Column(db.String(50))
    initialProductType = db.Column(db.String(50))
    firstName = db.Column(db.String(50))
    lastName = db.Column(db.String(50))
    dateOfBirth = db.Column(db.String(50))
    email = db.Column(db.String(50))
    address = db.Column(db.String(50))
    phoneNumber = db.Column(db.String(50))
